/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synel_synergy_synergy2416_jni_Synergy2416JNI_Synergy2416JNILoader */

#ifndef _Included_com_synel_synergy_synergy2416_jni_Synergy2416JNI_Synergy2416JNILoader
#define _Included_com_synel_synergy_synergy2416_jni_Synergy2416JNI_Synergy2416JNILoader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
