/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synel_synergy_synergy2416_jni_Synergy2416JNI */

#ifndef _Included_com_synel_synergy_synergy2416_jni_Synergy2416JNI
#define _Included_com_synel_synergy_synergy2416_jni_Synergy2416JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    helpInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_helpInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    getBatteryStatusCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_getBatteryStatusCode
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    setWatchDog
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_setWatchDog
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    takePicture
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_takePicture
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    takePictures
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_takePictures
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    initVolume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_initVolume
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    setVolume
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_setVolume
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    printData
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_printData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    readMAC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_readMAC
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    setMAC
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_setMAC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    readWigand
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_readWigand
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    readCardSector
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_readCardSector
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    writeCardSector
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_writeCardSector
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    writeCardKey
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_writeCardKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    redON
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_redON
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    redOFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_redOFF
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    greenON
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_greenON
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    greenOFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_greenOFF
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    modemON
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_modemON
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    modemOFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_modemOFF
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    relayON
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_relayON
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    relayOFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_relayOFF
  (JNIEnv *, jobject);

/*
 * Class:     com_synel_synergy_synergy2416_jni_Synergy2416JNI
 * Method:    doorBellPressed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_synel_synergy_synergy2416_jni_Synergy2416JNI_doorBellPressed
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
