/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synel_synergy_synergy2416_presentation_controller_FPU_FPULoader */

#ifndef _Included_com_synel_synergy_synergy2416_presentation_controller_FPU_FPULoader
#define _Included_com_synel_synergy_synergy2416_presentation_controller_FPU_FPULoader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
