/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synel_synergy_synergyX_presentation_controller_FPU */

#ifndef _Included_com_synel_synergy_synergyX_presentation_controller_FPU
#define _Included_com_synel_synergy_synergyX_presentation_controller_FPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    REDON
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_REDON
  (JNIEnv *, jclass);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    REDOFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_REDOFF
  (JNIEnv *, jclass);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    GREENON
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_GREENON
  (JNIEnv *, jclass);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    GREENOFF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_GREENOFF
  (JNIEnv *, jclass);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_OPENDEVICE
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1OPENDEVICE
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_CLOSEDEVICE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1CLOSEDEVICE
  (JNIEnv *, jclass);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_ENROLE_EMPLOYEE
 * Signature: (Ljava/lang/String;IJJLcom/synel/synergy/synergyX/presentation/api/FingerPrintEnrollmentHandler;)I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1ENROLE_1EMPLOYEE
  (JNIEnv *, jclass, jstring, jint, jlong, jlong, jobject);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_GET_BADGE_STATUS
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1GET_1BADGE_1STATUS
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_VALIDATE_EMPLOYEE
 * Signature: (Ljava/lang/String;IJI)I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1VALIDATE_1EMPLOYEE
  (JNIEnv *, jclass, jstring, jint, jlong, jint);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_DELETE_TEMPLATE
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1DELETE_1TEMPLATE
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_GET_BADGES
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1GET_1BADGES
  (JNIEnv *, jclass);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_GET_ENROLECOUNT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1GET_1ENROLECOUNT
  (JNIEnv *, jclass);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_GET_TEMPLATE
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1GET_1TEMPLATE
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_SET_TEMPLATE
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1SET_1TEMPLATE
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_IDENTIFY_EMPLOYEE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1IDENTIFY_1EMPLOYEE
  (JNIEnv *, jclass);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_DELETE_TEMPLATE_ALL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1DELETE_1TEMPLATE_1ALL
  (JNIEnv *, jclass);

/*
 * Class:     com_synel_synergy_synergyX_presentation_controller_FPU
 * Method:    FP_IDENTIFY_EMPLOYEE_MOCK
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_synel_synergy_synergyX_presentation_controller_FPU_FP_1IDENTIFY_1EMPLOYEE_1MOCK
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
